<?php
define('LANG','value');
define('HEADS_TOTAL','Heads Total');
define('TO_PAY','To Pay');
define('TO_RECEIVE','To Receive');
define('AVAILABLE_TOTAL','Available Total');
define('GENERAL_LEDGER','General Ledger');
define('ADD_ENTRY','Add Entry');
define('ID','ID');
define('INVOICE_ID','Inovice ID');
define('CUSTOMER_SUPPLIER','Customer/Supplier');
define('AMOUNT','Amount');
define('TOTAL_PAID','Total Paid');
define('TOTAL_RECEIVED','Total Received');
define('BALANCE','Balance');
define('EDIT','Edit');
define('VIEW_ALL','View All');
define('DASHBOARD','Dashboard');
define('SETTINGS','Settings');
define('LOGOUT','Logout');
define('DEPARTMENT','Departments');
define('EMPLOYEE_POSTS','Employee Posts');
define('EMPLOYEE_DEPARTMENTS','Employee Departments');
define('EMPLOYEE','Employees');
define('EMPLOYEE_ATTENDANCE','Employee Attendance');
define('EMPLOYEE_LEAVES','Employee Leaves');
define('EMPLOYEE_PERFORMANCE','Employee Performance');
define('EMPLOYEE_PAY_RECORDS','Employee Pay Records');
define('ACCOUNTS','Accounts');
define('DAY_BO0K','Day Book');
define('LEDGERS','Ledgers');
define('GENERAL_LEDGERS','General Ledgers');
define('ADVANCES_AND_LOANS','Advances & Loans');
define('ACCOUNT_HEADS','Account Heads');
define('BANK_ACCOUNTS_AND_LEDGERS','Bank Accounts & Ledgers');
define('PROCUREMENT_AND_ASSETS','Procurement & Assets');
define('CSM','CSM');
define('CRM','CRM');
define('CUSTOMER_LEDGER','Customer Ledger');
define('SUPPLIER_LEDGER','Supplier Ledger');
define('ACCOUNTS_RECEIVABLE','Accounts Receivable');
define('ACCOUNTS_PAYABLE','Accounts Payable');
define('REPORTING','Reporting');
define('TRIAL_BALANCE','Trial Balance');
define('BALANCE_SHEET','Balance Sheet');
define('PROFIT_AND_LOSS','Profit & Loss');
define('PROJECT_WISE_REPORT','Project-wise report');
define('JOB_WISE_REPORT','Job-wise report');
define('VENDORS_AND_CUSTOMERS','Vendors & Customers');
define('ADVANCES_AND_LOANS','Advances & Loans');
define('COMPANY_LIQUIDATION','Company Liquidation');
define('MISC_SETTINGS','Misc. Settings');
define('LEAVE_SETTINGS','Leave Settings');
define('PRIVACY_POLICY','Privacy Policy');
define('TERMS_AND_CONDITIONS','Terms and conditions');
define('LOGS','Logs');
define('EMPLOYEES_ADD_HISTORY','Employees Add History');
define('LOGGED_IN_HISTORY','Logged In History');
define('EVENT_CHANGES_LOG','Event Changes Log');
define('DATA_IMPORT_AND_EXPORT','Data Import & Export');
define('IMPORT_DATA','Import Data');
define('EXPORT_DATA','Export Data');
define('USERS','Users');
define('ADMINISTRATORS','Administrators');
define('CONTENT','Content');
define('TASK_LIST','Task List');
define('ADD_ACCOUNT_HEAD','Add Account Head');
define('AMOUNT_AVAILABLE','Amount Available');
define('OVER_ALL_TOTAL','Over All Total');
define('TOTAL_BALANCE','Total Balance');
define('LIST_OF_ALL_ACCOUNTS_RECEIVABLES','List of All Accounts Receivables.');
define('CUSTOMER_NAME','Customer Name');
define('RECEIVED','Received');
define('DATE','Date');
define('HEAD_CODE','Head Code');
define('HEAD_TYPE','Head Type');
define('HEAD_DESCRIPTION','Head Description');
define('LANG','value');
define('LANG','value');
define('LANG','value');
define('LANG','value');
define('LANG','value');
define('LANG','value');
?>
<?php //echo LIST_OF_ALL_ACCOUNTS_RECEIVABLES;?>